### ISSUE TITLE
SMuFLBuilder issue on Windows 11

### ISSUE THREAD

**Issue by NorFonts** [knutnergaard/FontLab-Scripts#3]
Hi Knut!

I've tried to setup your SMuFlBuilder on Windows 11 along with Python 2.7 and FL5.2 installed, here are the configuration of the files:

<img width="706" alt="CleanShot 2022-05-21 at 19 45 13@2x" src="https://user-images.githubusercontent.com/66909976/169665232-a4e37536-c893-40f5-8605-13abfd1ad3a0.png">

<img width="879" alt="CleanShot 2022-05-21 at 19 46 03@2x" src="https://user-images.githubusercontent.com/66909976/169665244-29c48d10-b408-4446-b67d-b05ac931786e.png">

<img width="784" alt="CleanShot 2022-05-21 at 19 46 44@2x" src="https://user-images.githubusercontent.com/66909976/169665282-6f696eb5-e641-4a60-abfb-9bf904de70c9.png">

When I run FL5.2, I load Bravura font then run the macro : SMuFLbuilder.py I get this error message in the FL5 output:

**`Unable to read settings: C:\Usersoreddinebahha\Documents\SMuFLbuilder Settings\smuflbuilder.ini`**

I'm really glad to try your scripts, they are the best!!!

Thanks for your reply in advance.
—Nor Eddine Bahha

**Comment by NorFonts** [comment]
I'm mostly a macOS user, I'm also running Windows 11 via Parallel Desktop 17 to run FontLab5.2. 

Below my configurations:

![CleanShot 2022-05-22 at 12 43 44@2x](https://user-images.githubusercontent.com/66909976/169693431-0a2e43d0-6517-435a-abb4-d1098209ef54.png)

![CleanShot 2022-05-22 at 12 47 10@2x](https://user-images.githubusercontent.com/66909976/169693771-ce700a69-7bd4-48e7-b55a-1dbc5f9df174.png)

**Comment by knutnergaard** [comment]
Hi, Nordine!

It's been quite a while since smuflbuilder or any other python scripts for FontLab have on my mind, so forgive me if I'm asking some obvious or stupid questions.

Also, I haven't actually tested the software on Windows yet, but that shouldn't matter, at least not in theory.

1. Make sure to reset the script before running it. There is a `reset macro` button to the left of the `edit macro` button inside FontLab. 

2. Are you sure that the module folder `smuflbuilder` is in the correct path? 
The FL manual for windows suggests `C:\Documents and Settings\Your Username\My Documents\FontLab\Studio5\Macro\System\Modules`, although it also states that the path of the user data folder can be changed in **Options > Folders and Paths > FontLab Studio 5 files**, so you need to make sure that these specifications match.

3. Are you also sure that the `SMuFL` folder containing the main script `smuflbuilder.py` is in the `[user data folder]\Macro`?

4. Even though your specified file paths in `filepaths.py` should be ok, please double check that the settings files are actually in the specified locations.

5. If it still won't work after checking all this, try reverting back to the original settings files `defaults.ini` and `smuflbuider.ini` and see if the script throws an error when not making any changes.

**Comment by NorFonts** [comment]
Hi Knut!

I will try your suggestions and get back to you with detailed infos. Thanks

**Comment by NorFonts** [comment]
Knut!

Here is a gif video showing all the paths and directories as you described in your .md file.

https://norfonts.ma/en/CleanShot%202022-05-22%20at%2014.00.05.gif

**Comment by NorFonts** [comment]
...and here is another gif video showing how FL5 fetch the error message:

https://norfonts.ma/en/CleanShot%202022-05-22%20at%2015.02.00.gif

**Comment by knutnergaard** [comment]
Nordine,

I get a 403 error when trying to play the gifs.

**Comment by NorFonts** [comment]
Try again, please.

**Comment by NorFonts** [comment]
Knut, I think I found the bug, I wrote above that:

```
When I run FL5.2, I load Bravura font then run the macro : SMuFLbuilder.py I get this error message in the FL5 output:
Unable to read settings: C:\Usersoreddinebahha\Documents\SMuFLbuilder Settings\smuflbuilder.ini
```

So the missing \n in the path: C:\Usersoreddinebahha\Documents\SMuFLbuilder Settings\smuflbuilder.ini is the problem maybe, I will need to change my Windows user name :-/ to something else ??? maybe ....

I found this too: 

In Python, the new line character “\n” is used to create a new line. When inserted in a string all the characters after the character are added to a new line. Essentially the occurrence of the “\n” indicates that the line ends here and the remaining characters would be displayed in a new line.

**Comment by knutnergaard** [comment]
Thanks for documenting this so thoroughly!

I think you may be on to something. 

Try adding a simple 'r' at the start of both the file paths in `filepaths.py`, so that the whole line reads: document reads:

```
defaults = r'C:\Users\noreddinebahha\Documents\Fontlab\Studio 5\Macros\System\Modules\smuflbuilder\defaults.ini'

user = r'C:\Users\noreddinebahha\Documents\SMuFLbuilder Settings\smuflbuilder.ini'
```

**Comment by NorFonts** [comment]
Well, I changed my username from noreddinebahha to camilbesma but still getting the same error:

Unable to read settings: C:\Users\camilbesma\Documents\SMuFLbuilder Settings\smuflbuilder.ini

**Comment by NorFonts** [comment]
> Thanks for documenting this so thoroughly!
> 
> I think you may be on to something.
> 
> Try adding a simple 'r' at the start of both the file paths in `filepaths.py`, so that the whole line reads: document reads:
> 
> `defaults = r'C:\Users\noreddinebahha\Documents\Fontlab\Studio 5\Macros\System\Modules\smuflbuilder\defaults.ini'
> 
> # Change the filepath below to match the location of smuflbuilder_settings.ini.
> user = r'C:\Users\noreddinebahha\Documents\SMuFLbuilder Settings\smuflbuilder.ini'

OK.

**Comment by knutnergaard** [comment]
If that doesn't work, could you attach the `defaults.ini` and `smuflbuilder.ini` you're using?
Or just include a screenshot of the first page of each.

**Comment by NorFonts** [comment]
[smuflbuilder.zip](https://github.com/knutnergaard/FontLab-Scripts/files/8749842/smuflbuilder.zip)
[defaults.zip](https://github.com/knutnergaard/FontLab-Scripts/files/8749844/defaults.zip)

these ones?

**Comment by NorFonts** [comment]
I'm still getting the same error message, even I added the 'r'.

**Comment by knutnergaard** [comment]
Yeah, and your .ini files look fine too.

I have no idea why this is happening, so I will have to do some testing on Windows myself. Unfortunately I'm rather swamped at the moment, so I don't know when I will get to it, but I'll report back as soon as I can.

Thanks for all your help and I'm sorry for the malfunction.

**Comment by NorFonts** [comment]
It's my pleasure Knut to test your stuff. That will help me a lot. 

Just explain me more, will SMuFLBuilder take for example Maestro font and make it SMuFL ? I'm confused... :-D

**Comment by NorFonts** [comment]
Reinstalled SMuFLBuilder from scratch, it's now working with the extra added 'r'. Thanks a lot KNUT!

**Comment by knutnergaard** [comment]
Great!
I've updated the docs with new instructions to reset the script when making settings changes as well.
